# Install requirements

In [1]:
!pip install numpy

  Using cached numpy-1.23.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)


# Import libs

In [3]:
import numpy as np

# Task1

Calculating pi by the Monte Carlo method:

In [4]:
n_points = 10000000

In [5]:
points = 2 * np.random.rand(n_points, 2) - 1

In [6]:
points_in_circle = points[np.sum(points ** 2, axis=1) <= 1]

In [7]:
n_points_in_circle = points_in_circle.shape[0]

In [8]:
n_points_in_circle

7853472

In [9]:
pi = 4 * n_points_in_circle / n_points
pi

3.1413888

In [11]:
print(f'Pi = {pi}')

Pi = 3.1413888


# Task 2

In [3]:
n = np.linspace(2, 99, 98)

In [4]:
import itertools as it

In [37]:
all_combinations = np.array(list(it.combinations_with_replacement(n, 2)))

In [45]:
# get pairs, that have not unique product
def first_condition(candidates):
    prods = np.prod(candidates, axis=1)
    unique, counts = np.unique(prods, return_counts=True)
    dict_counts = dict(zip(unique, counts))
    mask = np.array([dict_counts[x] != 1 for x in prods])
    return candidates[mask]

# check all possible sums, where all pairs of terms haven't unique product
# then return thats pairs
def second_condition(candidates):
    sums = np.sum(candidates, axis=1)
    unique = np.unique(sums)
    ix = [np.where(sums == i) for i in unique]
    candidates = [candidates[i[0]] for i in ix if candidates[i[0]][-1][0] == candidates[i[0]].shape[0] + 1]
    return np.concatenate(candidates, axis=0)

# return pairs that have unique product
def third_condition(candidates):
    prods = np.prod(candidates, axis=1)
    unique, counts = np.unique(prods, return_counts=True)
    dict_counts = dict(zip(unique, counts))
    mask = np.array([dict_counts[x] == 1 for x in prods])
    return candidates[mask]

# return pairs that have unique sum
def fourth_condition(candidates):
    sums = np.sum(candidates, axis=1)
    unique, counts = np.unique(sums, return_counts=True)
    dict_counts = dict(zip(unique, counts))
    mask = np.array([dict_counts[x] == 1 for x in sums])
    return candidates[mask]

In [46]:
r1 = first_condition(all_combinations)
r2 = second_condition(r1)
r3 = third_condition(r2)
r4 = fourth_condition(r3)
r4

array([[ 4., 13.]])

The solution is (4; 13)

## Searching solution

In [5]:
combinations = np.array(list(it.combinations_with_replacement(n, 2)))

In [6]:
prods = np.prod(combinations, axis=1)
prods

array([4.000e+00, 6.000e+00, 8.000e+00, ..., 9.604e+03, 9.702e+03,
       9.801e+03])

In [7]:
prods[200:300]

array([ 36.,  40.,  44.,  48.,  52.,  56.,  60.,  64.,  68.,  72.,  76.,
        80.,  84.,  88.,  92.,  96., 100., 104., 108., 112., 116., 120.,
       124., 128., 132., 136., 140., 144., 148., 152., 156., 160., 164.,
       168., 172., 176., 180., 184., 188., 192., 196., 200., 204., 208.,
       212., 216., 220., 224., 228., 232., 236., 240., 244., 248., 252.,
       256., 260., 264., 268., 272., 276., 280., 284., 288., 292., 296.,
       300., 304., 308., 312., 316., 320., 324., 328., 332., 336., 340.,
       344., 348., 352., 356., 360., 364., 368., 372., 376., 380., 384.,
       388., 392., 396.,  25.,  30.,  35.,  40.,  45.,  50.,  55.,  60.,
        65.])

In [8]:
unique, counts = np.unique(prods, return_counts=True)

In [9]:
dict_counts = dict(zip(unique, counts))

In [10]:
mask = np.array([dict_counts[x] != 1 for x in prods])
mask

array([False, False, False, ..., False, False, False])

In [11]:
combinations_1 = combinations[mask]
combinations_1

array([[ 2.,  6.],
       [ 2.,  8.],
       [ 2.,  9.],
       ...,
       [84., 88.],
       [84., 91.],
       [88., 90.]])

In [12]:
sums = np.sum(combinations_1, axis=1)
sums

array([  8.,  10.,  11., ..., 172., 175., 178.])

In [13]:
unique = np.unique(sums)

In [14]:
ix = [np.where(sums == i) for i in unique]

In [15]:
len(ix)

171

In [16]:
candidates = [combinations_1[i[0]] for i in ix if combinations_1[i[0]][-1][0] == combinations_1[i[0]].shape[0] + 1]

In [17]:
candidates

[array([[2., 9.],
        [3., 8.],
        [4., 7.],
        [5., 6.]]),
 array([[ 2., 15.],
        [ 3., 14.],
        [ 4., 13.],
        [ 5., 12.],
        [ 6., 11.],
        [ 7., 10.],
        [ 8.,  9.]]),
 array([[ 2., 21.],
        [ 3., 20.],
        [ 4., 19.],
        [ 5., 18.],
        [ 6., 17.],
        [ 7., 16.],
        [ 8., 15.],
        [ 9., 14.],
        [10., 13.],
        [11., 12.]]),
 array([[ 2., 25.],
        [ 3., 24.],
        [ 4., 23.],
        [ 5., 22.],
        [ 6., 21.],
        [ 7., 20.],
        [ 8., 19.],
        [ 9., 18.],
        [10., 17.],
        [11., 16.],
        [12., 15.],
        [13., 14.]]),
 array([[ 2., 27.],
        [ 3., 26.],
        [ 4., 25.],
        [ 5., 24.],
        [ 6., 23.],
        [ 7., 22.],
        [ 8., 21.],
        [ 9., 20.],
        [10., 19.],
        [11., 18.],
        [12., 17.],
        [13., 16.],
        [14., 15.]]),
 array([[ 2., 33.],
        [ 3., 32.],
        [ 4., 31.],
        [ 5., 30.]

In [29]:
combinations_2 = np.concatenate(candidates, axis=0)

In [21]:
prods_step_3 = np.prod(combinations_2, axis=1)

In [26]:
unique, counts = np.unique(prods_step_3, return_counts=True)

In [27]:
dict_counts = dict(zip(unique, counts))

In [31]:
mask = np.array([dict_counts[x] == 1 for x in prods_step_3])
mask

array([ True,  True,  True, False, False, False,  True, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False,  True, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True,  True, False,
       False, False,  True,  True, False,  True,  True,  True, False,
       False, False, False, False,  True,  True, False, False,  True,
        True, False, False,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False,  True, False,  True,  True, False, False,  True, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True, False,
        True, False,

In [32]:
combinations_3 = combinations_2[mask]
combinations_3

array([[ 2.,  9.],
       [ 3.,  8.],
       [ 4.,  7.],
       [ 4., 13.],
       [ 4., 19.],
       [ 7., 16.],
       [10., 13.],
       [ 2., 25.],
       [ 4., 23.],
       [ 5., 22.],
       [ 7., 20.],
       [ 8., 19.],
       [ 9., 18.],
       [10., 17.],
       [11., 16.],
       [13., 14.],
       [ 2., 27.],
       [ 4., 25.],
       [ 6., 23.],
       [ 7., 22.],
       [ 8., 21.],
       [10., 19.],
       [11., 18.],
       [12., 17.],
       [13., 16.],
       [ 3., 32.],
       [ 4., 31.],
       [ 6., 29.],
       [ 8., 27.],
       [ 9., 26.],
       [10., 25.],
       [12., 23.],
       [14., 21.],
       [16., 19.],
       [17., 18.],
       [ 5., 32.],
       [ 6., 31.],
       [ 8., 29.],
       [ 9., 28.],
       [10., 27.],
       [16., 21.],
       [17., 20.],
       [ 3., 38.],
       [ 4., 37.],
       [ 7., 34.],
       [ 9., 32.],
       [10., 31.],
       [12., 29.],
       [13., 28.],
       [14., 27.],
       [15., 26.],
       [16., 25.],
       [17.,

In [33]:
len(combinations_3)

86

In [34]:
sums_step_4 = np.sum(combinations_3, axis=1)
sums_step_4

array([11., 11., 11., 17., 23., 23., 23., 27., 27., 27., 27., 27., 27.,
       27., 27., 27., 29., 29., 29., 29., 29., 29., 29., 29., 29., 35.,
       35., 35., 35., 35., 35., 35., 35., 35., 35., 37., 37., 37., 37.,
       37., 37., 37., 41., 41., 41., 41., 41., 41., 41., 41., 41., 41.,
       41., 41., 41., 47., 47., 47., 47., 47., 47., 47., 47., 47., 47.,
       47., 47., 47., 53., 53., 53., 53., 53., 53., 53., 53., 53., 53.,
       53., 53., 53., 53., 53., 53., 53., 53.])

In [35]:
sums_step_4 = np.sum(combinations_3, axis=1)
sums_step_4

array([11., 11., 11., 17., 23., 23., 23., 27., 27., 27., 27., 27., 27.,
       27., 27., 27., 29., 29., 29., 29., 29., 29., 29., 29., 29., 35.,
       35., 35., 35., 35., 35., 35., 35., 35., 35., 37., 37., 37., 37.,
       37., 37., 37., 41., 41., 41., 41., 41., 41., 41., 41., 41., 41.,
       41., 41., 41., 47., 47., 47., 47., 47., 47., 47., 47., 47., 47.,
       47., 47., 47., 53., 53., 53., 53., 53., 53., 53., 53., 53., 53.,
       53., 53., 53., 53., 53., 53., 53., 53.])

In [36]:
unique, counts = np.unique(sums_step_4, return_counts=True)